export const defaultBlogPosts = [
  {
    id: "wp-4700",
    slug: "types-of-threads-used-in-kente",
    title: "3 Types of Threads Used in Kente: A Buyer's Guide to Quality",
    excerpt: "A buyer's guide to Rayon, Polyester, and Silk threads used in Kente.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2026/07/Rayon-Kente-Thread-768x576.jpeg",
    publish_at: "2026-07-07T18:51:18.000Z",
  },
  {
    id: "wp-4675",
    slug: "kente-belt",
    title: "The Kente Belt: Understanding the Art and Craftmanship of the Owontoma in the Kente Artistery",
    excerpt: "A closer look at the Kente belt, the vertical strip lines that shape a finished cloth.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2026/05/featured-image-768x383.jpg",
    publish_at: "2026-05-26T13:11:40.000Z",
  },
  {
    id: "wp-4637",
    slug: "in-appreciation-of-nana-konadu-agyeman-rawlings",
    title: "In Appreciation of Nana Konadu Agyeman-Rawlings",
    excerpt: "A Hinkro Kente tribute to Nana Konadu Agyeman-Rawlings and her cultural influence.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2025/11/WhatsApp-Image-2025-10-23-at-14.37.23-400x470-1.webp",
    publish_at: "2025-11-28T15:20:21.000Z",
  },
  {
    id: "wp-4627",
    slug: "kente-officially-protected-as-a-national-treasure",
    title: "Ghana Makes History: Kente Officially Protected as a National Treasure",
    excerpt: "Kente cloth receives Geographical Indication status as a protected Ghanaian craft.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2025/10/IMG_1149-768x1024.jpg",
    publish_at: "2025-10-11T19:00:22.000Z",
  },
  {
    id: "wp-4294",
    slug: "kente-for-organizational-groups-and-corporate-businesses",
    title: "Kente for Organizational Groups and Corporate Businesses: Elevate Your Brand with Culture and Class",
    excerpt: "How organizations can use Kente to express identity, culture, and brand distinction.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2025/05/Kente-for-organizational-groups-and-corporate-businesses-768x1152.png",
    publish_at: "2025-05-17T11:58:09.000Z",
  },
  {
    id: "wp-4278",
    slug: "black-star-experience",
    title: "Ghana Launches the Black Star Experience to Rebrand as Africa's Cultural Powerhouse",
    excerpt: "Ghana positions culture and creativity through the Black Star Experience.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2025/05/WhatsApp_Image_2025_05_02_at_18_24_42_1746207699-768x512.jpeg",
    publish_at: "2025-05-04T19:32:26.000Z",
  },
  {
    id: "wp-4266",
    slug: "kente-and-kitenge",
    title: "Kente vs Kitenge: Unraveling the Threads of African Textile Heritage",
    excerpt: "A comparison of two iconic African textiles and their cultural roots.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2025/05/Kente-vs-kitenge-768x371.jpg",
    publish_at: "2025-05-03T23:30:46.000Z",
  },
  {
    id: "wp-4022",
    slug: "developing-kente-pattern-for-weaving",
    title: "Hinkro Kente: Leading the way in developing Kente Patterns for Weaving",
    excerpt: "How pattern development keeps Kente connected to tradition and modern design.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2024/09/Developing-Kente-patterns-01-768x379.jpg",
    publish_at: "2024-09-28T12:59:08.000Z",
  },
  {
    id: "wp-4015",
    slug: "african-artifact",
    title: "African Artifact: A Timeless Expression of Cultural Heritage",
    excerpt: "African artifacts as bridges between history, belief, memory, and craft.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2024/09/PHOTO-2023-08-11-15-11-49-768x805.jpg",
    publish_at: "2024-09-09T00:46:28.000Z",
  },
  {
    id: "wp-3947",
    slug: "computerized-kente-pattern",
    title: "The Art of Computerized Pattern Generation in Modern Kente Weaving",
    excerpt: "How technology supports modern Kente pattern design.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2024/08/212f15fb772ef8314c2014a4793f5a6e.jpg",
    publish_at: "2024-08-25T21:53:35.000Z",
  },
  {
    id: "wp-3903",
    slug: "kente-in-your-own-colors",
    title: "Getting Kente in Your Own Colors with Hinkro Kente",
    excerpt: "How bespoke Kente can be woven around your own preferred colours.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2024/07/kente-in-your-own-colors-01.png",
    publish_at: "2024-07-31T12:30:29.000Z",
  },
  {
    id: "wp-3817",
    slug: "the-timeless-allure-of-the-fatia-fata-nkrumah-kente-cloth",
    title: "The Timeless Allure of the Fatia Fata Nkrumah Kente Cloth",
    excerpt: "A classic Kente design with national and cultural resonance.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/01/ezgif-4-b74b64afe6-768x512.webp",
    publish_at: "2024-07-15T20:24:48.000Z",
  },
  {
    id: "wp-3783",
    slug: "ombre-kente-transitional-inspirations",
    title: "10 Beautiful Nature Gradient Transitional Images That You Can Use for Ombre Kente",
    excerpt: "Nature-gradient inspiration for ombre Kente colour transitions.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2024/07/a08b14aec911469ad2987101d8a6bd8c.jpg",
    publish_at: "2024-07-15T00:24:07.000Z",
  },
  {
    id: "wp-3752",
    slug: "custom-kente-stole",
    title: "Hinkro: The Premier Destination for Custom Kente Stoles",
    excerpt: "Custom Kente stoles woven for ceremonies, graduation, and identity.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/05/kente-stole-st-thomas-768x512.webp",
    publish_at: "2024-07-13T00:10:51.000Z",
  },
  {
    id: "wp-2884",
    slug: "value-to-kente",
    title: "How Hinkro Kente Adds Value to Kente Cloth and Custom Weaving",
    excerpt: "How bespoke service, craft, and finishing elevate custom Kente weaving.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2024/05/Josephine-Kente-1-768x1277.jpg",
    publish_at: "2024-05-26T19:53:45.000Z",
  },
  {
    id: "wp-2877",
    slug: "kente",
    title: "Kente: All you need to know about Ghana's Kente Fabric",
    excerpt: "An introduction to Kente fabric, its origin, patterns, and cultural value.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2024/05/Kente-768x959.jpg",
    publish_at: "2024-05-24T00:36:53.000Z",
  },
  {
    id: "wp-2865",
    slug: "ankara-fabric-and-kente-fabric",
    title: "Ankara Fabric vs. Kente Fabric: History, Production, and Design",
    excerpt: "A look at two celebrated African textiles and what makes each distinct.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2024/05/Ankara-fabric-768x408.jpg",
    publish_at: "2024-05-23T23:59:52.000Z",
  },
  {
    id: "wp-2851",
    slug: "wesley-girls-high-school-187-anniversary",
    title: "Kente in grand display as Wesley Girls High School marks 187th Anniversary",
    excerpt: "A school anniversary celebration marked with Kente, heritage, and tradition.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2024/02/426724029_708478601420402_7402506763002739886_n-768x580.jpg",
    publish_at: "2024-02-16T20:51:03.000Z",
  },
  {
    id: "wp-2839",
    slug: "black-star-kente",
    title: "Black Stars' Dazzling Entrance in Ivory Coast in Vibrant Kente Cloth",
    excerpt: "Ghana's national football team makes a cultural statement in Kente.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2024/01/b31aaf5da71baca3-768x384.jpg",
    publish_at: "2024-01-16T19:06:02.000Z",
  },
  {
    id: "wp-2801",
    slug: "kente-weaver",
    title: "KENTE WEAVER IN GHANA",
    excerpt: "A guide for finding skilled Kente weaving craftsmanship in Ghana.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/12/Kente-weaver.jpg",
    publish_at: "2023-12-29T19:27:26.000Z",
  },
  {
    id: "wp-2720",
    slug: "discover-the-finest-kente-buying-experience-in-the-uk-with-hinkro-kente",
    title: "Discover the Finest Kente Buying Experience in the UK with Hinkro Kente",
    excerpt: "A guide for clients buying authentic Kente in the United Kingdom.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/03/134482763_358390612181587_636861046390924332_n.jpeg",
    publish_at: "2023-08-15T14:15:26.000Z",
  },
  {
    id: "wp-2704",
    slug: "exploring-the-distinctive-charms-of-kente-and-ankara-fabrics",
    title: "Exploring the Distinctive Charms of Kente and Ankara Fabrics",
    excerpt: "A comparison of Kente and Ankara through history, patterns, and cultural meaning.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/08/Kente-vs-Ankara.jpg",
    publish_at: "2023-08-12T19:31:20.000Z",
  },
  {
    id: "wp-2677",
    slug: "rediscovering-history-the-revamped-kwame-nkrumah-memorial-park",
    title: "Rediscovering History: The Revamped Kwame Nkrumah Memorial Park",
    excerpt: "A reflection on one of Ghana's landmark spaces for history and heritage.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/07/IMG_1560-768x576.jpg",
    publish_at: "2023-07-27T10:01:22.000Z",
  },
  {
    id: "wp-2665",
    slug: "crafting-the-perfect-kente-a-comprehensive-guide-to-authentic-african-kente-fabric",
    title: "Crafting the Perfect Kente: A Comprehensive Guide to Authentic African Kente Fabric",
    excerpt: "A guide to the history, significance, and craftsmanship behind authentic African Kente fabric.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/07/Bonwire-Kente-weaving-village-768x542.jpg",
    publish_at: "2023-07-01T11:51:18.000Z",
  },
  {
    id: "wp-2661",
    slug: "where-to-buy-kente-fabric-online-in-the-usa",
    title: "Where to Buy Kente Fabric Online in the USA",
    excerpt: "A guide for buying authentic African Kente fabric online in the USA.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/07/il_570xN.3150892239_syk3.webp",
    publish_at: "2023-07-01T11:11:11.000Z",
  },
  {
    id: "wp-2518",
    slug: "unveiling-the-radiance-of-ombre-kente",
    title: "Ombre Kente - Unveiling the Radiance of traditional textile",
    excerpt: "A look at ombre Kente and the visual appeal of gradient transitions.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/06/download.jpg",
    publish_at: "2023-06-21T10:59:42.000Z",
  },
  {
    id: "wp-2488",
    slug: "kente-cloth-2",
    title: "Kente Cloth: Unveiling the Vibrant Tapestry of Ghanaian Culture",
    excerpt: "An introduction to Kente cloth as a symbol of Ghanaian culture.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/06/117663696_lv3-768x432.jpg",
    publish_at: "2023-06-04T00:10:06.000Z",
  },
  {
    id: "wp-2452",
    slug: "why-obama-kente",
    title: "Why Obama Kente?",
    excerpt: "A short background on the Kente design associated with Barack Obama.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/05/106_27-768x512.jpg",
    publish_at: "2023-05-15T19:37:48.000Z",
  },
  {
    id: "wp-2449",
    slug: "dansinkran-kente-wrapped-kente-cloth",
    title: "Dansinkran: Wrapped Kente cloth",
    excerpt: "The art of wrapping Kente cloth for engagement and ceremonial styling.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/05/f7fc6581652b2b182bee2de50b158458-768x475.jpg",
    publish_at: "2023-05-15T18:48:02.000Z",
  },
  {
    id: "wp-2443",
    slug: "kente-graduation-stole-significance-in-black-academics",
    title: "Kente Graduation Stole: Significance in Black Academics",
    excerpt: "The meaning and pride carried by Kente graduation stoles.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/05/kente-stole-st-thomas-768x512.webp",
    publish_at: "2023-05-15T17:34:24.000Z",
  },
  {
    id: "wp-2225",
    slug: "how-kente-cloths-are-made",
    title: "How Kente Cloths Are Made",
    excerpt: "An overview of the traditional weaving process behind Kente cloth.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2023/03/pexels-tope-a-asokere-3592348-768x576.jpeg",
    publish_at: "2023-04-09T13:36:53.000Z",
  },
  {
    id: "wp-100",
    slug: "kente-cloth-colors",
    title: "The True Meaning Of Kente Cloth Colors",
    excerpt: "A look at colour symbolism and meaning in Kente cloth.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2016/11/Types-Of-Kente-Cloth-In-Ghana-And-Origin-.jpg",
    publish_at: "2016-11-28T13:06:31.000Z",
  },
  {
    id: "wp-97",
    slug: "kente-2",
    title: "Kente: 7 Things You Need To Know",
    excerpt: "Seven essentials for understanding Kente cloth and its cultural importance.",
    featured_image: "https://www.hinkrokente.com/wp-content/uploads/2016/11/KENTE-9-768x542.jpg",
    publish_at: "2016-11-28T13:03:14.000Z",
  },
  {
    id: "wp-3918",
    slug: "case-study-crafting-a-bespoke-kente-for-client-josephine-by-hinkro-kente",
    title: "Case Study: Crafting a Bespoke Kente for Client Josephine by Hinkro Kente",
    excerpt: "A bespoke ombre kente transitioning from olive green to gold and grey for a discerning client.",
    featured_image: null,
    publish_at: "2024-07-31T21:56:40.000Z",
  },
  {
    id: "wp-2859",
    slug: "ghana-month",
    title: "Celebrate Ghana month with the Rich Tradition of Kente by Hinkro Kente",
    excerpt: "March is the Ghana month! Join the festivities by adorning yourself in the magnificent Kente fabric.",
    featured_image: null,
    publish_at: "2024-03-20T17:38:11.000Z",
  },
  {
    id: "wp-2702",
    slug: "kente-cloth",
    title: "What is Kente Cloth",
    excerpt: "Kente cloth stands as an icon of African culture, a fabric that weaves together intricate artistry, vibrant symbolism, and a rich heritage.",
    featured_image: null,
    publish_at: "2023-08-12T19:09:55.000Z",
  },
];
